networks:
  network_dpaas:

services:
  # Base de données utilisée pour l'authentification par token
  db:
    container_name: dpass_db
    image: mariadb
    restart: unless-stopped
    networks:
      - network_dpaas
    environment:
      MYSQL_DATABASE: auth
      MYSQL_USER: dpaas
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Génération TTS par IA
  xtts:
    container_name: dpass_xtts
    build: ./xtts
    image: dpass_xtts-api-server:latest
    restart: unless-stopped
    networks:
      - network_dpaas
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: auth
      DB_USER: dpaas
      DB_PASS: ${MYSQL_PASSWORD}
    volumes:
      - ./logs/xtts:/var/log/xtts/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "5000:5000"

  # Génération de vidéos par IA
  face-animator:
    container_name: dpass_face-animator
    build: ./face-animator
    image: dpass_face-animator:latest
    restart: unless-stopped
    networks:
      - network_dpaas
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: auth
      DB_USER: dpaas
      DB_PASS: ${MYSQL_PASSWORD}
    volumes:
      - ./logs/face-animator:/var/log/face-animator/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "5000:5000"

  # Bot
  melenchon:
    container_name: dpass_melenchon
    build: ./bot
    image: dpaas_bot:latest
    restart: unless-stopped
    depends_on:
      - xtts
    networks:
      - network_dpaas
    environment:
      XTTS_ENDPOINT: "http://xtts:5000/api/generate"
      DPAAS_TOKEN: ${MELENCHON_TOKEN_DPAAS}
      VOICE: "melenchon-light"
      VOICEFILTER: "phone"
      INITIATEUR: "true" # Est-ce que le bot initie la conversation après un !reset ?
      OPENAI_API_KEY: ${MELENCHON_TOKEN_OPENAI}
      DISCORD_API_KEY: ${MELENCHON_TOKEN_DISCORD}
      PREPROMPT: "Comporte toi comme Jean-Luc Mélenchon sur Discord. Adopte un vocabulaire courant, et ne parle pas beaucoup. Soit à la limite de l'insolence. Ton interlocuteur est Eric Zemmour. Utilise le pronom vous pour parler de lui."

  # Bot
  zemmour:
    container_name: dpass_zemmour
    build: ./bot
    image: dpaas_bot:latest
    restart: unless-stopped
    depends_on:
      - xtts
    networks:
      - network_dpaas
    environment:
      XTTS_ENDPOINT: "http://xtts:5000/api/generate"
      DPAAS_TOKEN: ${ZEMMOUR_TOKEN_DPAAS}
      VOICE: "zemmour-light"
      VOICEFILTER: "phone"
      OPENAI_API_KEY: ${ZEMMOUR_TOKEN_OPENAI}
      DISCORD_API_KEY: ${ZEMMOUR_TOKEN_DISCORD}
      PREPROMPT: "Comporte toi comme Eric Zemmour sur Discord. Adopte un vocabulaire courant, et ne parle pas beaucoup. Soit à la limite de l'insolence. Ton interlocuteur est Jean-Luc Mélenchon. Utilise le pronom vous pour parler de lui."